export default function MockSFHIRPatient(){
    return {
        "resourceType": "Patient",
        "id": "bd7cb541-732b-4e39-ab49-ae507aa49326",
        "meta": {
            "versionId": "1",
            "lastUpdated": "2018-05-07T13:09:34.014-04:00",
            "tag": [
                {
                    "system": "https://smarthealthit.org/tags",
                    "code": "synthea-8-2017"
                }
            ]
        },
        "text": {
            "status": "generated",
            "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>. Version identifier: 1a8d765a5375bf72f3b7a92001940d05a6f21189</div>"
        },
        "extension": [
            {
                "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
                "valueCodeableConcept": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v3/Race",
                            "code": "2106-3",
                            "display": "White"
                        }
                    ],
                    "text": "race"
                }
            },
            {
                "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
                "valueCodeableConcept": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v3/Ethnicity",
                            "code": "2186-5",
                            "display": "Nonhispanic"
                        }
                    ],
                    "text": "ethnicity"
                }
            },
            {
                "url": "http://hl7.org/fhir/StructureDefinition/birthPlace",
                "valueAddress": {
                    "city": "Bridgewater",
                    "state": "MA",
                    "country": "US"
                }
            },
            {
                "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
                "valueString": "Sona Krajcik"
            },
            {
                "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
                "valueCode": "F"
            },
            {
                "url": "http://hl7.org/fhir/StructureDefinition/patient-interpreterRequired",
                "valueBoolean": false
            }
        ],
        "identifier": [
            {
                "system": "https://github.com/synthetichealth/synthea",
                "value": "605ff918-1784-4a11-b4f3-1c1ba6e07f51"
            },
            {
                "type": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/identifier-type",
                            "code": "SB"
                        }
                    ]
                },
                "system": "http://hl7.org/fhir/sid/us-ssn",
                "value": "999476570"
            },
            {
                "type": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v2/0203",
                            "code": "DL"
                        }
                    ]
                },
                "system": "urn:oid:2.16.840.1.113883.4.3.25",
                "value": "S99982899"
            },
            {
                "type": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v2/0203",
                            "code": "PPN"
                        }
                    ]
                },
                "value": "X44425666X"
            },
            {
                "type": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v2/0203",
                            "code": "MR"
                        }
                    ]
                },
                "system": "http://hospital.smarthealthit.org",
                "value": "605ff918-1784-4a11-b4f3-1c1ba6e07f51"
            }
        ],
        "name": [
            {
                "use": "official",
                "family": [
                    "Feeney"
                ],
                "given": [
                    "Arie"
                ],
                "prefix": [
                    "Mrs."
                ]
            },
            {
                "use": "maiden",
                "family": [
                    "Schneider"
                ],
                "given": [
                    "Arie"
                ]
            }
        ],
        "telecom": [
            {
                "system": "phone",
                "value": "1-851-256-2372 x811",
                "use": "home"
            }
        ],
        "gender": "female",
        "birthDate": "1927-07-14",
        "deceasedDateTime": "2008-01-17T16:08:22-05:00",
        "address": [
            {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                        "extension": [
                            {
                                "url": "latitude",
                                "valueDecimal": 42.21690245266151
                            },
                            {
                                "url": "longitude",
                                "valueDecimal": -71.79490155461701
                            }
                        ]
                    }
                ],
                "line": [
                    "165 Homenick Crest"
                ],
                "city": "Worcester",
                "state": "MA",
                "postalCode": "01613",
                "country": "US"
            }
        ],
        "maritalStatus": {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/v3/MaritalStatus",
                    "code": "M"
                }
            ],
            "text": "M"
        },
        "multipleBirthBoolean": false,
        "communication": [
            {
                "language": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/ValueSet/languages",
                            "code": "en-US",
                            "display": "English (United States)"
                        }
                    ]
                }
            }
        ]
    }
}